# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fumoffu}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lionel Abderemane"]
  s.date = %q{2011-04-19}
  s.default_executable = %q{fumoffu}
  s.description = %q{I will make the description later}
  s.email = %q{alionel@gmail.com}
  s.executables = ["fumoffu"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/fumoffu",
    "lib/fumoffu.rb",
    "lib/fumoffu/controller.rb",
    "lib/fumoffu/generators/fumoffu_config_generator.rb",
    "lib/fumoffu/generators/fumoffu_generator.rb",
    "lib/fumoffu/generators/fumoffu_lib_generator.rb",
    "lib/fumoffu/generators/fumoffu_src_generator.rb",
    "lib/fumoffu/generators/tasks/generator.rake",
    "lib/fumoffu/generators/tasks/install.rake",
    "lib/fumoffu/generators/tasks/package.rake",
    "lib/fumoffu/generators/templates/Gemfile",
    "lib/fumoffu/generators/templates/Rakefile",
    "lib/fumoffu/generators/templates/build_configuration.rb",
    "lib/fumoffu/generators/templates/engine/config/initializers/app_classes.rb",
    "lib/fumoffu/generators/templates/engine/config/initializers/configuration.rb",
    "lib/fumoffu/generators/templates/engine/config/initializers/init.rb",
    "lib/fumoffu/generators/templates/engine/config/initializers/java_classes.rb",
    "lib/fumoffu/generators/templates/engine/config/initializers/ruby_classes.rb",
    "lib/fumoffu/generators/templates/engine/src/actions/controllers/application_controller.rb",
    "lib/fumoffu/generators/templates/engine/src/actions/handlers/application_handler.rb",
    "lib/fumoffu/generators/templates/engine/src/main.rb",
    "lib/fumoffu/generators/templates/engine/src/setup.rb",
    "lib/fumoffu/generators/templates/engine/test/spec/spec_helper.rb",
    "lib/fumoffu/generators/templates/interface/lib/AbsoluteLayout.jar",
    "lib/fumoffu/generators/templates/interface/lib/SwingLayout.jar",
    "lib/fumoffu/generators/templates/interface/src/org/github/bouba/fumoffu/ActionManager.java",
    "lib/fumoffu/generators/templates/interface/src/org/github/bouba/fumoffu/UIActions.java",
    "lib/fumoffu/generators/templates/interface/src/org/rubyforge/rawr/Main.java",
    "lib/fumoffu/generators/templates/scripts/package.sh",
    "lib/fumoffu/generators/templates/scripts/start.sh",
    "lib/fumoffu/handler.rb",
    "lib/fumoffu/java_mapping.rb",
    "lib/fumoffu/utils/component_search.rb",
    "tasks/rawr_bundle.rake",
    "test/coverage/index.html",
    "test/coverage/jquery-1.3.2.min.js",
    "test/coverage/jquery.tablesorter.min.js",
    "test/coverage/lib-fumoffu-controller_rb.html",
    "test/coverage/lib-fumoffu-generators-fumoffu_config_generator_rb.html",
    "test/coverage/lib-fumoffu-generators-fumoffu_generator_rb.html",
    "test/coverage/lib-fumoffu-generators-fumoffu_lib_generator_rb.html",
    "test/coverage/lib-fumoffu-generators-fumoffu_src_generator_rb.html",
    "test/coverage/lib-fumoffu-handler_rb.html",
    "test/coverage/lib-fumoffu-java_mapping_rb.html",
    "test/coverage/lib-fumoffu-utils-component_search_rb.html",
    "test/coverage/lib-fumoffu_rb.html",
    "test/coverage/print.css",
    "test/coverage/rcov.js",
    "test/coverage/screen.css",
    "test/fumoffu/fumoffu_controller_test.rb",
    "test/fumoffu/fumoffu_test.rb",
    "test/fumoffu/generators/fumoffu_config_generator_test.rb",
    "test/fumoffu/generators/fumoffu_generator_test.rb",
    "test/fumoffu/generators/fumoffu_lib_generator_test.rb",
    "test/fumoffu/generators/fumoffu_src_generator_test.rb",
    "test/fumoffu/handler_test.rb",
    "test/fumoffu/helper.rb",
    "test/fumoffu/helper/generator_test_helper.rb",
    "test/fumoffu/java_mapping_test.rb",
    "test/fumoffu/utils/component_search_test.rb"
  ]
  s.homepage = %q{http://github.com/bouba/fumoffu}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{A JRuby / Java Swing framework to easily build portable GUI application}
  s.test_files = [
    "test/fumoffu/fumoffu_controller_test.rb",
    "test/fumoffu/fumoffu_test.rb",
    "test/fumoffu/generators/fumoffu_config_generator_test.rb",
    "test/fumoffu/generators/fumoffu_generator_test.rb",
    "test/fumoffu/generators/fumoffu_lib_generator_test.rb",
    "test/fumoffu/generators/fumoffu_src_generator_test.rb",
    "test/fumoffu/handler_test.rb",
    "test/fumoffu/helper.rb",
    "test/fumoffu/helper/generator_test_helper.rb",
    "test/fumoffu/java_mapping_test.rb",
    "test/fumoffu/utils/component_search_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_runtime_dependency(%q<jruby-openssl>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0.10.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.10"])
      s.add_dependency(%q<jruby-openssl>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0.10.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.10"])
    s.add_dependency(%q<jruby-openssl>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0.10.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

